version: '3'

services:

    cache:
        image: redis:latest
        container_name: redis
        ports:
          - 6379:6379
  
    api:
        container_name: api
        build: '.'
        links:
            - cache:cache
        command: /app/api
        ports:
            - 8000:8000
        environment:
            - TOKEN_SECRET=mySecretJWT
            - CACHE_HOST=cache
            - DB_HOST=database
            - DB_USER=root
            - DB_PASSWORD=toor
            - TRACE_HOST=jaeger:14268
        depends_on:
            - database
            - cache
            - jaeger
        restart: always

    database:
        image: "mysql:5.7.24"
        container_name: database
        command:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "toor"
            MYSQL_DATABASE: "auth"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "pass"
        
    jaeger:
        image: jaegertracing/all-in-one:1.22.0
        container_name: jaeger
        ports:
            - "14268:14268"   # jaeger-collector HTTP server (tracer provider)
            - "16686:16686"   # HTTP server (browser UI)