version: '3.8'

services:

    cache:
        image: redis:latest
        container_name: redis
        ports:
          - 6379:6379
  
    api:
        container_name: make-deals-api
        build: '.'
        links:
            - cache:cache
        command: /app/api
        ports:
            - 8081:8080
        environment:
            - CACHE_HOST=cache
            - SAVE_QUEUE=sqs-lno-queue